name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("edgeR","methods", "Matrix"), repos="https://cloud.r-project.org")'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install .[tests,rpy2]

      - name: Run pytest
        run: pytest -q
