name: Test the library

on:
  push:
    branches:
      - master # for legacy repos
      - main
  pull_request:
    branches:
      - master # for legacy repos
      - main
  workflow_dispatch: # Allow manually triggering the workflow
  schedule:
    # Run roughly every 15 days at 00:00 UTC
    # (useful to check if updates on dependencies break the package)
    - cron: "0 0 1,16 * *"

jobs:
  test:
    strategy:
      matrix:
        python: ["3.11","3.12","3.13"]
        platform:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    name: Python ${{ matrix.python }} on ${{ matrix.platform }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # ─── NEW: Install R ───────────────────────────────────────────────────────
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install required R/Bioconductor packages
        run: |
          # install BiocManager if it isn’t already
          Rscript -e 'if (!requireNamespace("BiocManager", quietly=TRUE)) \
                         install.packages("BiocManager", repos="https://cloud.r-project.org")'
          # now install edgeR (and any other Bioconductor pkgs) non-interactively
          Rscript -e 'BiocManager::install(
                         c("edgeR", "Matrix"),
                         ask=FALSE, 
                         update=FALSE
                       )'

      # ─── Existing Python setup ───────────────────────────────────────────────
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install tox coverage rpy2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coverage rpy2
          # now install your package in editable mode, bringing in the "tests" extra
          pip install -e .[tests]

      - name: Run tests
        run: |
          pipx run --python '${{ steps.setup-python.outputs.python-path }}' \
            tox \
            -- \
            -rFEx --durations 10 --color yes --cov --cov-branch --cov-report=xml

      - name: Check for codecov token
        id: codecov-check
        run: |
          if [ -n "${{ secrets.CODECOV_TOKEN }}" ]; then
            echo "codecov=true" >> $GITHUB_OUTPUT; else
            echo "codecov=false" >> $GITHUB_OUTPUT; fi

      - name: Upload coverage
        if: steps.codecov-check.outputs.codecov == 'true'
        uses: codecov/codecov-action@v5
        with:
          flags: ${{ matrix.platform }}-py${{ matrix.python }}
          token: ${{ secrets.CODECOV_TOKEN }}


